<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="checkDesignatedStockService"
     targetNamespace="http://oracle.com/sca/soapservice/mysqlTestInsert/CheckDesignatedStockServ/checkDesignatedStockService"
     xmlns:tns="http://oracle.com/sca/soapservice/mysqlTestInsert/CheckDesignatedStockServ/checkDesignatedStockService"
     xmlns:inp1="http://www.kpei.co.id/CheckDesignatedStock"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.kpei.co.id/CheckDesignatedStock" schemaLocation="xsd/DataFeedTradeCheckDesignatedStock.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="input" element="inp1:NettedTrade"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="out" element="inp1:NettedTrade"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="designatedStock_execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
