<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="checkDesignatedStockService" targetNamespace="http://oracle.com/sca/soapservice/mysqlTestInsert/CheckDesignatedStockServ/checkDesignatedStockService" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://oracle.com/sca/soapservice/mysqlTestInsert/CheckDesignatedStockServ/checkDesignatedStockService" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <plnk:partnerLinkType name="checkDesignatedStockRef">
      <plnk:role name="execute_ptt">
         <plnk:portType name="tns:execute_ptt"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://oracle.com/sca/soapservice/mysqlTestInsert/CheckDesignatedStockServ/checkDesignatedStockService" location="http://soavhn1.corp.kpei.co.id:7777/soa-infra/services/MW/CheckDesignatedStockServ/checkDesignatedStockService.wsdl"/>
</wsdl:definitions>
