<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ftpDataTradeDummy" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ARIS-KPEI-PROJECT/OR08-DataFeedTrade/ftpDataTradeDummy" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ARIS-KPEI-PROJECT/OR08-DataFeedTrade/ftpDataTradeDummy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://www.kpei.co.id/InboundService" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="Put_plt">
      <plt:role name="Put_role">
         <plt:portType name="tns:Put_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.kpei.co.id/InboundService" schemaLocation="xsd/DataTradeDummy.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="Put_msg">
      <wsdl:part name="body" element="imp1:fields"/>
   </wsdl:message>
   <wsdl:portType name="Put_ptt">
      <wsdl:operation name="Put">
         <wsdl:input message="tns:Put_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
