<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="REF_CA_insert" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR08-DataFeedTrade/REF_CA_insert" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR08-DataFeedTrade/REF_CA_insert" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/REF_CA_insert">
   <plt:partnerLinkType name="REF_CA_insert_plt">
      <plt:role name="REF_CA_insert_role">
         <plt:portType name="tns:REF_CA_insert_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/REF_CA_insert" schemaLocation="xsd/REF_CA_insert_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CorporateActionsHisCollection_msg">
      <wsdl:part name="CorporateActionsHisCollection" element="top:CorporateActionsHisCollection"/>
   </wsdl:message>
   <wsdl:portType name="REF_CA_insert_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:CorporateActionsHisCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
